### ISSUE TITLE
Incompatibility with bevy_ecs_ldtk / bevy_ecs_tilemap

### ISSUE THREAD

**Issue by 19lmyers** [drakmaniso/bevy_pixel_camera#25]
I've been having a problem where tiles from my tilemap (from the crate bevy_ecs_ldtk, which uses the crate bevy_ecs_tilemap) don't render, but only when using the camera provided by this crate. The default Camera2D bundle does not exhibit this issue.

**Comment by drakmaniso** [comment]
I'm not sure what could be the problem, it should work... Is there some code you could show?

**Comment by 19lmyers** [comment]
I don't think I do anything special, I just used one of the LDTK samples and imported it with bevy_ecs_ldtk.

**Comment by drakmaniso** [comment]
I've just tried all the examples of bevy_ecs_ldtk. "basic" and "traitless" worked correctly. In the "level_set" example, half of the tiles are rendered gray, while the other half is fine... And in the "platformer" example, all the level tiles are rendered gray, but the free floating entities are rendered correctly...

I'm not sure what is happening...

**Comment by 19lmyers** [comment]
Yeah, I was using the platformer example. I'm honestly not experienced enough to know what the issue might be, but could it have something to do with how near and far are swapped? I could be completely wrong though.
I did also read that bevy_ecs_ldtk may have some remaining issues with z-indexing, which could be related (see https://github.com/Trouv/bevy_ecs_ldtk/issues/174)

**Comment by drakmaniso** [comment]
Yes, this could be a problem with z-indexing, but I've just checked for differences between my code and bevy's Camera2dBundle, and I didn't see anything relevant...

**Comment by drakmaniso** [comment]
The incompatibility seems to be with bevy_ecs_tilemap, as some of their examples do not render correctly either.

I still don't see what could be the problem since most of the components used in bevy_pixel_camera are standard Bevy components. The only new component, `PixelProjection`, is very close to bevy's `OrthographicProjection` and implements the required trait. Maybe bevy_ecs_tilemap is not generic over cameras and projections (i.e. it depends directly on `Camera2dBundle` or `OrthographicProjection`), but I didn't find anything in their code to suggest that this is the case.

**Comment by xentripetal** [comment]
The issue seems to be with the projection not being registered in the visibility plugin https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/view/visibility/mod.rs#L220

You can partially fix the issue with implementing the update_frusta systems

```rust
        app.add_system(update_frusta::<PixelProjection>
            .in_set(UpdateProjectionFrusta)
            .after(camera_system::<PixelProjection>)
            .after(TransformSystem::TransformPropagate)
            .ambiguous_with(update_frusta::<OrthographicProjection>)
            .ambiguous_with(update_frusta::<Projection>)
        );
```

though I am seeing some tile layers flickering with this, so its likely not the complete solution. I will post an update if I figure it out.

**Comment by drakmaniso** [comment]
Thanks! I'll publish a new version with the fix shortly.
