### ISSUE TITLE
Text2dBundle anti-aliasing

### ISSUE THREAD

**Issue by halfhorst** [drakmaniso/bevy_pixel_camera#7]
I just started using the pixel camera and it's been great! However, I've noticed that text (using `Text2dBundle`) is rendering with some kind of anti-aliasing, which I'm trying to avoid. It's particularly bad when the glyphs are small. The builtin orthographic camera doesn't appear to do this. I'm assuming this has something to do with the scaling that the pixel camera is doing but I'm not really sure how to fix it. I was wondering if you knew what the issue may be. 

Below are examples from both cameras. The white text is rendered from a font. Top is the pixel camera, bottom is the ortho camera

![pixel_camera](https://user-images.githubusercontent.com/1770961/165679389-1cc4dee5-0361-40fe-8a65-654daffd0d7f.png)

![ortho_camera](https://user-images.githubusercontent.com/1770961/165679391-e0b38657-e48c-4772-b2ee-5e9fd8b03681.png)
.

**Comment by drakmaniso** [comment]
Hi, thanks for the feedback, but I don't understand the problem... Both your images seem to show the same anti-aliasing around the white text? It's less visible in the bottom one because the text is scaled bigger, but the same grey outline is there, with a width of 1 pixel (actual screen pixel, not virtual).

I suppose this is a truetype font that simulates a pixel font? I'm not sure if it's possible to achieve a pixel perfect look this way in bevy (I haven't tried, though).

**Comment by halfhorst** [comment]
Yeah you're correct, it's an OTF font that is pixelated. And yeah, I played around more, there seems to be anti-aliasing going on in both. Something to do with how the font is rendered. If I size up the font and downscale with a transform, it crisps up under the pixel camera. Thanks for your response! I'm going to close this, there isn't a clear issue or direction
